# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ScanCode' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ScanCode
pod 'Masonry', '~> 1.1.0'
pod 'AFNetworking', '~> 3.1.0'
pod 'UMengAnalytics-NO-IDFA', '~> 4.2.5'
pod 'YYText', '~> 1.0.7'

  target 'ScanCodeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ScanCodeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
